apiVersion: v1
kind: PersistentVolume
metadata:
  name: opendj-local
spec:
  storageClassName: opendj-local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/kube/pv/opendj
