apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  type: ClusterIP
  selector:
    app: ldap
  ports:
    - protocol: TCP
      name: ldap
      port: 1389
      targetPort: 1389
    - protocol: TCP
      name: ldaps
      port: 1636
      targetPort: 1636
    - protocol: TCP
      name: admin
      port: 4444
      targetPort: 4444
