apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opendj
  labels:
    name: opendj
spec:
  serviceName: opendj
  replicas: 1
  selector:
    matchLabels:
      app: opendj
  template:
    metadata:
      labels:
        app: opendj
    spec:
      initContainers:
      - name: volume-mount
        image: busybox
        command: ["sh", "-c", "chown -R 1001:999 /data"]
        volumeMounts:
          - name: opendj-data
            mountPath: /data
      containers:
        - name: opendj
          image: openidentityplatform/opendj:4.4.7
          resources:
            requests:
              memory: 2Gi
          ports:
          - name: ldap
            containerPort: 1389
          - name: ldaps
            containerPort: 1636
          - name: admin
            containerPort: 4444
          env:
          - name: ADD_BASE_ENTRY
            valueFrom:
              configMapKeyRef:
                name: opendj
                key: add_base_entry
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: opendj
                key: port
          - name: LDAPS_PORT
            valueFrom:
              configMapKeyRef:
                name: opendj
                key: ldaps_port
          - name: BASE_DN
            valueFrom:
              configMapKeyRef:
                name: opendj
                key: base_dn
          - name: ROOT_USER_DN
            valueFrom:
              configMapKeyRef:
                name: opendj
                key: root_user_dn
          - name: ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opendj
                key: root_password
          - name: OPENDJ_REPLICATION_TYPE
            valueFrom:
              configMapKeyRef:
                name: opendj
                key: opendj_replication_type
          volumeMounts:
          - name: opendj-data
            mountPath: /opt/opendj/data
          - name: java-properties
            mountPath: /tmp/java.properties
            subPath: java.properties
            readOnly: true
      volumes:
      - name: opendj-data
        persistentVolumeClaim:
          claimName: opendj-local
      - name: java-properties
        configMap:
          name: opendj-java-properties
